/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dist_info_CONSTANTS_H
#define dist_info_CONSTANTS_H

#include "dist_info_types.h"



class dist_infoConstants {
 public:
  dist_infoConstants();

};

extern const dist_infoConstants g_dist_info_constants;



#endif
