/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dist_info_constants.h"



const dist_infoConstants g_dist_info_constants;

dist_infoConstants::dist_infoConstants() {
}



